name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-agent:
    name: PR-Agent Review
    runs-on: ubuntu-latest
    concurrency:
      group: pr-agent-${{ github.event.pull_request.number }} 
      cancel-in-progress: true
    if: >
        github.event_name == 'pull_request' &&
        github.event.pull_request.draft == false &&
        github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Run PR-Agent
        uses: Codium-ai/pr-agent@d82f7d3e696cd00822694aaa3096265d3889f3f1
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AGENT.PR_DESCRIPTION: "true"
          PR_AGENT.PR_REVIEWER: "true"
          PR_AGENT.PR_CODE_SUGGESTIONS: "true"
          github_action_config.pr_actions: '["opened","reopened","ready_for_review","synchronize"]'
